var new_lang = {

  "lt0": "News",
"lt1": "Geschichten",
"lt2": "Analysen",
"lt3": "Spiele",
"lt4": "Chat",
"lt5": "Analysen",
"lt6": "Mit Fürsorge um Menschen. Der weltweit berühmte Kardiologe Alexander Schmidt erklärte, warum  Menschen mit niedrigem Blutdruck keine Chance haben, gesund zu werden. ",
"lt7": "Meduza",
"lt8": " Alexander Schmidt ist ein ausgezeichneter Facharzt, Gewinner des Gairdner Foundation International Awards und langjähriger Mitarbeiter einer Klinik für Herz-Kreislauf-Erkrankungen.",
"lt9": " Alexander Schmidt ist ein ungewöhnlicher Kardiologe, der bescheiden lebt und immer versucht, Menschen zu helfen. In diesem Winter reinigte der weltberühmte Kardiologe selbst den Schnee in der Nähe der Klinik, in der er und seine Kollegen jeden Tag Kindern und Erwachsenen das Leben retteten. Dieses Kardiologiezentrum gilt als eines der besten der Welt. Menschen aus aller Welt lassen sich dort behandeln. Die Klinik führte erstmals eine künstliche Herztransplantation durch und rettete Tausenden Menschen das Leben.",
"lt10": "Eines der wichtigsten Merkmale von Alexander Schmidt ist die Ablehnung von Business und Täuschung, insbesondere bei der Behandlung der Hypotonie und Herzerkrankungen. Er hält sich wie ein echter Arzt strikt an den in unserer Zeit seltenen Eid des Hippokrates.",
"lt11": "Daher ist es besonders alarmierend von diesem weltberühmten Kardiologen  zu hören, dass sich DIE MEDIZIN IN UNSEREM LAND MINDESTENS UM 20 JAHRE ZURÜCKBLEIBT UND DASS MENSCHEN MIT DER HYPOTONIE KEINE CHANCE HABEN, IHREN NIEDRIGEN BLUTRUCK ZU HEILEN.",
"lt12": "Wir hatten es zwar nicht leicht ein Interview von diesem Kardiologen zu erhalten, haben es dennoch aber geschafft. Hier ist das interview.",
"lt13": "- Herr Schmidt, könnten Sie bitte Ihre Aussagen über die Medizin in unserem Land kommentieren?",
"lt14": "- Ja, natürlich. Ich bin es gewohnt offen und ehrlich über Probleme zu sprechen. Leider gibt es in unserem Land heute einfach keine Medizin. Genauer gesagt kann man das, was heute bei uns existiert, nicht als Medizin bezeichnen. Dass, was in Kliniken und Krankenhäusern vor sich geht, ist schrecklich. Die Ärzte sind entweder schon zu alt oder noch zu jung und unerfahren. Alle mehr oder weniger kompetenten Ärzte  arbeiten in Privatkliniken. Dort geht es aber in erster Linie ums Geschäft.  90% der Ärzte sind korrupt. Sie interessieren sich nur nicht dafür, wie man seinen Patienten helfen kann, sondern möchten so viel Geld wie möglich aus ihnen herausholen. ",
"lt15": "Schauen Sie sich nur die Kosten für einen Termin bei einer Person mit einem Doktortitel  in der Medizin an. Ab 5000 Euro für eine Beratung! Wie viel wird dann eine Behandlung kosten? ",
"lt16": "Woher sollen einfach Menschen so viel Geld haben? Dabei ist es für die Ärzte von Vorteil, dass so viele Menschen krank sind. Niemand ist an einer schnellen und vollständigen Genesung von Menschen interessiert. ",

"lt17": "Das Schlimmste ist aber, was in Apotheken verkauft wird. Ich kann nicht von allen Medikamenten sprechen, sondern nur von diejenigen,  die für die die Behandlung von Herz-Kreislauf-Erkrankungen und der Hypotonie verschrieben werden. Das sind 30-Jahre alte  Medikamente, neue Medikamente gibt es einfach nicht! ",
"lt18": "Sie werden überrascht sein, wenn ich Ihnen sage, dass DIE HYPOTONIE SCHON LANGE ALS EINE CHRONISCHE KRANKHEIT GILT UND SICH  ERFOLGREICH BEHANDELN LÄSST. Überall auf der Welt, aber nicht in unserem Land. ",
"lt19": "Bei uns werden immer noch solche Medikamente, wie <b>Andipal, Valoserdin, Atenalol, Enap, Arifon, Atenol, Diltiazem, Mildronat, Lozap, Amlodipin</b> usw. verwendet. Zum Einen sind sie schon ziemlich alt und zum Anderen sind sie nicht zur Behandlung der Hypotonie bestimmt. Sie ermöglichen es nur den  Blutdruck nur vorübergehend zu normalisieren und ihn nicht loszuwerden. Das bedeutet, dass man immer die Hälfte seine Gehalts für Medikamente ausgeben muss.",
"lt20": "Diese Medikamente sollen nur vorübergehend den Blutdruck erhöhen, sie beseitigen aber nicht die Ursachen der Hypotonie!",
"lt21": "In fortgeschrittenen Ländern werden diese Medikamente nicht mehr verwendet  und werden selbst in Ländern der Dritten Welt auf ein Minimum reduziert. Warum sage ich „selbst“?  Weil unser Land schon immer für sein wissenschaftliches und medizinisches Potenzial bekannt war, viele weltberühmte Ärzte und Erfinder kommen aus unserem Land. Heute dreht sich aber alles ums Geld. Und das ist sehr traurig.",
"lt22": "- Wie wird die Hypotonie normalerweise in Industrieländern behandelt? Laut medizinischer Statistik ist die Zahl hypertensiver Patienten in Europa und Nordamerika in den letzten 5 Jahren um fast das Siebenfache gesunken. Ist es so? ",
"lt23": "- Das ist tatsächlich so. HYPOTONIE LÄSST SICH HEUTE GANZ EINFACH BEHANDELN. Dabei sollte man nicht nur die Symptome dieser Krankheit bekämpfen, sondern auch die Krankheitsursachen. Ich werde versuchen es so einfach wie möglich zu erklären. Stellen Sie sich Wasserrohre vor. Wenn sich die Rohre in einem saubere zustand befinden, kann Wasser ungehindert durch sie durchfließen.",
"lt24": "Unsere Gefäße sind darunter auch für die Kontraktion auf Nervenimpulse verantwortlich, die vom Gehirn ausgehen. Wenn dieses Gleichgewicht gestört ist, bleiben die Gefäße erweitert und es wird eine unzureichende Menge Aldosteron in den Nebennieren produziert, was den Druck erhöhen kann. Was wiederum bedeutet, dass der Blutdruck sinkt. ",
"lt25": "Um eine arterielle Hypotonie zu diagnostizieren, muss ein Patient zunächst untersucht werden, um eine Pathologie der Schilddrüse, Anämie und andere Krankheiten auszuschließen. In den meisten Fällen sind die Ursachen für eine Hypotonie eine gestörte Regulation der Nervenimpulse. Die Folge davon ist eine Verlangsamung der Durchblutung. Die Körperorgane erhalten nicht genügend Sauerstoff, was für das Gehirn besonders gefährlich ist. Es besteht eine ernsthafte Gefahr für den Menschen.",
"lt26": "Sauerstoffmangel (Hypoxie) des Gehirns ist eine der wichtigsten Ursachen für Herzinfarkte und Schlaganfälle",
"lt27": "Noch zu Beginn des 20. Jahrhunderts entdeckten Wissenschaftler eine einzigartige Behandlung der Hypotonie durch perkutane Elektroneurostimulation. Sie hilft bei der Reinigung von Blutgefäßen, einschließlich kleiner Kapillaren. Außerdem ähneln Stromimpulse den Impulsen menschlicher Nervenfasern. Aufgrund dieser Ähnlichkeit ist das Behandlungsverfahren mit perkutaner Elektroneurostimulation absolut schmerzfrei und ähnelt sogar einer leichten Massage. Mit dieser Entwicklung hört der Druck auf, ständig zu steigen und beginnt sich zu stabilisieren. Kopfschmerzen, Schläfrigkeit werden verschwinden, das Sehvermögen wird sich nicht mehr verschlechtern und die Nieren werden nicht zerstört.",
"lt28": "Das Risiko eines Herzinfarkts oder Schlaganfalls, der häufigsten Pathologie, an der bis zu 70% der Menschen mit niedrigem Blutdruck sterben, verschwindet.",
"lt29": "- Wie kann man solch eine Behandlung erhalten? Können Menschen mit der Hypotonie sich in Ihrer behandeln lassen? ",
"lt30": "- Das können sie natürlich auch machen – die Türen unseres Zentrums stehen allen offen. Ich werde Ihnen jetzt aber ein Geheimnis verraten – das brauchen sie überhaupt nicht zu tun, da es mittlerweile ein Gerät gibt, mit dem man die Hypotonie auch zu Hause behandeln kann. In Privatkliniken wird eine Behandlung des niedrigen Blutdrucks oft zehn mal teuer sein. ",
"lt31": "Das Gerät heißt XX. Seine Effektivität wurde wiederholt in klinischen Studien nachgewiesen. ",
"lt32": "- Sie haben doch von einem bedauerlichen Zustand unserer Medizin gesprochen? ",
"lt33": "- Ganz richtig. Es stellte sich heraus, dass in unserem Land niemand dieses Gerät benötigt. Weder korrupten Ärzten, noch den Apothekern. Gesunde  Menschen braucht in unserem Land niemand. Dieses Gerät werden Sie weder in Apotheken kaufen können, noch wird es Ihnen von unseren Ärzten verschrieben.  ",
"lt34": "Soweit ich weiß, hat der Hersteller versucht, dieses Gerät über Apotheken zu verkaufen, aber man hat es ihm nicht erlaubt.",
"lt35": "- Wo kann man XX dann kaufen?",
"lt36": "- Sie können XX auf der <a href=\"\">offiziellen Webseite dieses Geräts bestellen</a>. Wobei Sie dass auch noch zum ermäßigten Preis tun können!",
"lt37": "Die Bestellung des Geräts erfolgt sehr einfach. Dafür muss man folgendes tun:",
"lt38": "Auf die<a href=\"\">offizielle Webseite</a> übergehen und eine Anfrage hinterlassen.",
"lt39": "Warten Sie dann auf den Anruf den Kundenberaters, um weitere Details zu klären. Informieren den Kundenberater auch noch über ihren Blutdruck, Ihre weiteren Probleme, falls vorhanden und wie lange Sie schon an niedrigem Blutdruck leiden und welche Medikamente Sie einnehmen. Diese Informationen sind notwendig, damit wir die passende Behandlungsmethode  für Sie auswählen können. ",
"lt40": "Nach 2-5 Tagen müssen Sie zur Post kommen und das Paket erhalten. ",
"lt41": "Da XX erst vor kurzem in den Handel gekommen ist, sollte man berücksichtigen, dass die Nachfrage sehr hoch ist. Das Interessanteste ist, dass sein<b>Preis zehnmal günstiger ist jegliche Verfahren in Kliniken</b>.",
"lt42": "Seit dem Verkauf dieses Geräts sind bereits 3000 Personen mit niedrigem Blutdruck gesund geworden.",
"lt43": "Unsere Klinik war an den Ergebnissen der Verwendung des Geräts interessiert und führte eine unabhängige Studie durch. Hier sind die Ergebnisse unserer Umfrage.",
"lt44": "Der Blutdruck hat sich vollständig stabilisiert – 98% der Befragten",
"lt45": "Die Herzfrequenz hat sich normalisiert – 97% der Befragten",
"lt46": "Kopfschmerzen sind verschwunden – 99% der Befragten",
"lt47": "Das Sehvermögen hat sich verbessert – 74% der Befragten",
"lt48": "Deutliche Gesundheitsverbesserungen – 99% der Befragten",
"lt49": "Wie Sie sehen können, hilft XX fast allen. Wie ich bereits erwähnt habe, kann der die Hypotonie  damit vollständig und selbst im hohen Alter geheilt werden.  ",
"lt50": "- Wie lange wird XX Ihrer Meinung nach zu so einem niedrigen Preis verkauft werden?",
"lt51": "- Bis die vom Hersteller zugewiesene  Menge zu Ende geht. Ich möchte alle sofort warnen, dass es nicht mehr viele Geräte auf Lager gibt. In letzter Zeit erfahren immer mehr Menschen über die Wirksamkeit  dieser Behandlungsmethode und XX wird deshalb immer häufiger bestellt. Deshalb empfehle ich allen, die ihren niedrigen Blutdruck behandeln möchten XX so schnell, wie möglich zu bestellen. ",
"lt52": "Zur offiziellen Webseite übergehen, um XX zu bestellen",
"lt53": "Kommentare",
"lt54": "Matthias Klein",
"lt55": "Alle sprechen von schlechter Medizinversorgung, aber niemand möchte etwas dagegen unternehmen! Obwohl ich noch recht jung in, leide ich auch an niedrigem Blutdruck und werde mir dieses Gerät bestellen, vielleicht wird es mir ja helfen ",
"lt56": "Mia Bauer",
"lt57": "Egal, wie viel Medikamente ich auch einnehme, es wird dennoch nicht besser. Ist es vielleicht nur bei mir der Fall? Ein guter Bekannter von mir ist vor sechs Monaten an einem Herzinfarkt gestorben, wobei Ärzte ihm davor immer gesagt haben, dass die Hypotonie  nicht tödlich sei. Naja.",
"lt58": "Jakob Schneider",
"lt59": "Ich habe vor kurzem angefangen dieses Gerät zu benutzen und es hat mir in der Tat SEHR gut geholfen! Ich weiß gar nicht mehr, wann ich das letzte Mal meinen Blutdruck kontrolliert oder jegliche Medikamente eingenommen habe. :)",
"lt60": "Patrick Paul",
"lt61": "Ja, die Medizinversorgung in unserem Land ist nicht mehr so gut. Aber wir haben immer noch so wundervolle Ärzte und unsere Kanzlerin!",
"lt62": "Michael Neumann",
"lt63": "Ich habe seit meinem 50 Lebensjahr an der Hypotonie gelitten. Inzwischen bin ich 63 Jahre alt. Ein guter Bekannter von mir ist an der Herstellung dieses Gerät beteiligt, weshalb ich von Anfang an darüber informiert war und es sofort ausprobiert habe! Der Blutdruck hat sich in der Tat normalisiert! Ich fühle mich nun einfach großartig! Meine Enkelin hat es sich auch bestellt und auch ihr hat es sehr gut geholfen. Sieht dazu auch noch so gut aus!  :)",
"lt64": "Nicole Lange",
"lt65": "Vielen Dank. Sehr interessant. Ich habe auch eine Anfrage hinterlassen. Man hat mir versprochen es in 5 Tagen zu liefern. Das hoffe ich sehr",
"lt66": "Friederike Lehmann",
"lt67": "Das Hauptziel der Ärzte ist es, so viel Geld wie möglich aus uns herauszuholen. Sie sind an nichts anderem interessiert. Ich lass mich jedes halbe Jahr behandeln und es hilft mir immer noch nicht. Dieses Jahr hat man mir wieder die gleichen Medikamente verschrieben, ohne mich zu fragen, wie es mir geht. Was das Gerät betrifft, ist es eine sehr gute Nachricht! Danke! ",
"lt68": "Adriane Keller",
"lt69": "Habe mich auf der<a href=\"\">offiziellen Webseite</a> darüber informiert und erfahren, dass der Versand nur 5 Tage dauert. ",
"lt70": "Benjamin Günther",
"lt71": "XX hat mir sehr gut gefallen. Habe mich paar Monate damit behandeln lassen und die Hypotonie ist wirklich verschwunden! War sehr überrascht. Fühle mich einfach großartig und empfehle es allen weiter. ",
"lt72": "Jana Vogel",
"lt73": "Habe XX noch als einer der ersten auf der angegebenen Website bestellt.  Ein bekannter Kardiologe hat mir davon erzählt. Hatte bereits eine Hypotonie 3Grades und musste ständig Medikamente einnehmen. Der Blutdruck lag bei mir nur selten über der 75/40 Marke. Nun hat er sich vollständig normalisiert. XX ist die Erlösung! ",
"lt74": "Zur offiziellen Webseite übergehen, um XX zu bestellen",
"lt76": "Meduza",
"lt77": "Über das Projekt",
"lt79": "Warten Sie!<br>",
"lt80": "Wir haben ein zeitlich begrenztes Sonderangebot für Sie <br>ТNur bis zum <script type=\"text/javascript\">d = new Date(); p = new Date(d.getTime() - 0 * 86400000);monthA = 'Januar, Februar, März, April, Mai, Juni, Juli, August, September, Oktober, November, Dezember'.split(',');var w = p.getDate();document.write(p.getDate() + ' ' + monthA[p.getMonth()] + ' ' + p.getFullYear());</script>14. August 2020 können Sie das Gerät per Aktion erhaten!",
"lt81": "Erhalten",


  };
  function Translater () {
   for (class_name in new_lang) {
   var elements = document.getElementsByClassName(class_name);
   if (elements.length) {
   for (key in elements) {
   elements[key].innerHTML = new_lang[class_name];
   }
   }
   }
   };
  